### ISSUE TITLE
CTRL+L doesn't show upper segments

### ISSUE THREAD

**Issue by fedemengo** [yardnsm/blox-zsh-theme#8]
The issue arises when I'm clearing the screen. If I use `clear` it works perfectly (it clears the screen and both upper and lower segments are displayed) 

![before](https://user-images.githubusercontent.com/19249682/50039412-f4d59880-ffe6-11e8-8aac-160da559e513.png)

![clear](https://user-images.githubusercontent.com/19249682/50039417-074fd200-ffe7-11e8-81fc-235c0ef69449.png)

However, when I use `CTRL+L` the screen is cleared but the upper segments are not displayed

![ctrl l](https://user-images.githubusercontent.com/19249682/50039418-0e76e000-ffe7-11e8-94de-8e5ba55268c0.png)

Any idea on how I can fix this?

**Comment by yardnsm** [comment]
In order to fix some weird redrawing on resize issue (described in https://github.com/yardnsm/blox-zsh-theme/issues/2), some changes were made to the rendering mechanism (specifically https://github.com/yardnsm/blox-zsh-theme/commit/c2657726ebb96e75088d0e5ae702b36bac1b5781), which first prints the upper segment and sets `$PROMPT` to the lower segments. This is why then using `CTRL+L` only the lower segments get re-rendered.

We can set `$PROMPT` to also include the upper segments (like before the changes in https://github.com/yardnsm/blox-zsh-theme/commit/c2657726ebb96e75088d0e5ae702b36bac1b5781), but we'll get the resize problems back.

A solution for this could be some config variable to control this behaviour, but I can't think of one with a proper name 😋. Thoughts?

**Comment by fedemengo** [comment]
What about `UNIFIED_PROMPT`?

Thanks for the useful info, I've been doing some experiments and I understand why you decided to implement it this way. 
It seems that the redrawing-on-resize issue is a common problem to several themes
